# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742

In [11]:
print(f"The diameter of {planet} is {diameter} kilometers." )

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [31]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [37]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [38]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [50]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [52]:
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [59]:
import numpy as np
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [61]:
import numpy as np
array=np.arange(0,9).reshape((3,3))
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [64]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [65]:
import pandas as pd


In [79]:
data ={
     "product": ["earphone", "monitor", "keyboard"],
  "price": [100, 1500, 365]
}
df = pd.DataFrame(data)
print(df) 

    product  price
0  earphone    100
1   monitor   1500
2  keyboard    365


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [80]:
import calendar
yy = 2023 
mm = 1 2
d =1 to 10
print(calendar.month(yy, mm,d))

SyntaxError: ignored

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [81]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [83]:
import pandas as pd
df = pd.DataFrame(lists)
print(df)


   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
